<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubastaYa.Domain\SubastaYa.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\AuditLog\" />
    <Folder Include="Dtos\Bid\" />
    <Folder Include="Dtos\Category\" />
    <Folder Include="Dtos\Wallet\" />
    <Folder Include="Dtos\User\" />
    <Folder Include="Dtos\TransactionLedger\" />
    <Folder Include="UseCases\Bids\Commands\" />
    <Folder Include="UseCases\Categories\" />
    <Folder Include="UseCases\Wallets\" />
    <Folder Include="UseCases\Users\" />
    <Folder Include="UseCases\TransactionLedger\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

</Project>
